/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.2.0
 * Product:       stcc4
 * Model-Version: 3.4.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include "stcc4_i2c.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    stcc4_init(STCC4_I2C_ADDR_64);

    sensirion_hal_sleep_us(6000);
    // Ensure sensor is in idle state
    error = stcc4_exit_sleep_mode();
    if (error != NO_ERROR) {
        printf("error executing exit_sleep_mode(): %i\n", error);
        return error;
    }
    error = stcc4_stop_continuous_measurement();
    if (error != NO_ERROR) {
        printf("error executing stop_continuous_measurement(): %i\n", error);
        return error;
    }
    // Enter sleep mode
    error = stcc4_enter_sleep_mode();
    if (error != NO_ERROR) {
        printf("error executing enter_sleep_mode(): %i\n", error);
        return error;
    }
    int16_t co2_concentration = 0;
    float temperature = 0.0;
    float relative_humidity = 0.0;
    uint16_t status = 0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 100; repetition++) {
        //
        // Measure every 10 seconds.
        sensirion_hal_sleep_us(10000000);
        //
        // Exit sleep mode to put the sensor into idle mode
        // to be able to perform a single shot measurement
        error = stcc4_exit_sleep_mode();
        if (error != NO_ERROR) {
            printf("error executing exit_sleep_mode(): %i\n", error);
            continue;
        }
        //
        // If humidity/temperature and/or pressure compensation is
        // desired, you should call the respective compensation
        // functions here. Check-out the header file for the definition
        // of the compensation functions.
        //
        // Perform a single shot measurement and read the sensor data
        error = stcc4_measure_single_shot();
        if (error != NO_ERROR) {
            printf("error executing measure_single_shot(): %i\n", error);
            continue;
        }
        error = stcc4_read_measurement(&co2_concentration, &temperature,
                                       &relative_humidity, &status);
        if (error != NO_ERROR) {
            printf("error executing read_measurement(): %i\n", error);
            continue;
        }
        //
        // Power down the sensor to reduce power consumption.
        error = stcc4_enter_sleep_mode();
        if (error != NO_ERROR) {
            printf("error executing enter_sleep_mode(): %i\n", error);
            continue;
        }
        //
        // Print results as physical unit.
        printf("CO2 concentration [ppm] = %i\n", co2_concentration);
        printf("Temperature [°C] = %.2f\n", temperature);
        printf("Humidity [RH] = %.2f\n", relative_humidity);
        printf("Status = %u\n", status);
    }

    return NO_ERROR;
}
