/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.2.0
 * Product:       stcc4
 * Model-Version: 3.4.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include "stcc4_i2c.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    stcc4_init(STCC4_I2C_ADDR_64);

    uint32_t product_id = 0;
    uint64_t serial_number = 0;
    error = stcc4_stop_continuous_measurement();
    if (error != NO_ERROR) {
        printf("error executing stop_continuous_measurement(): %i\n", error);
        return error;
    }
    error = stcc4_get_product_id(&product_id, &serial_number);
    if (error != NO_ERROR) {
        printf("error executing get_product_id(): %i\n", error);
        return error;
    }
    printf("product_id: %u ", product_id);
    printf("serial_number: %" PRIx64 "\n", serial_number);
    error = stcc4_start_continuous_measurement();
    if (error != NO_ERROR) {
        printf("error executing start_continuous_measurement(): %i\n", error);
        return error;
    }
    int16_t co2_concentration = 0;
    float temperature = 0.0;
    float relative_humidity = 0.0;
    uint16_t sensor_status = 0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 50; repetition++) {
        sensirion_hal_sleep_us(1000000);
        error = stcc4_read_measurement(&co2_concentration, &temperature,
                                       &relative_humidity, &sensor_status);
        if (error != NO_ERROR) {
            // A read fail could be caused by clock shitfting, retry shifting
            // read by 150ms.
            printf("error executing read_measurement_raw(): %i. Retrying in "
                   "150ms.\n",
                   error);
            sensirion_hal_sleep_us(150000);

            error = stcc4_read_measurement(&co2_concentration, &temperature,
                                           &relative_humidity, &sensor_status);

            if (error != NO_ERROR) {
                printf(
                    "error executing read_measurement_raw() after retry: %i.\n",
                    error);
                continue;
            }
        }
        printf("co2_concentration: %i ", co2_concentration);
        printf("temperature: %.2f ", temperature);
        printf("relative_humidity: %.2f ", relative_humidity);
        printf("sensor_status: %u\n", sensor_status);
    }

    error = stcc4_stop_continuous_measurement();
    if (error != NO_ERROR) {
        return error;
    }
    return NO_ERROR;
}
